# Generated by Django 3.2 on 2023-02-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
