# Generated by Django 3.2 on 2023-02-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveSmallIntegerField(choices=[('شنبه', 1), ('یکشنبه', 2), ('دوشنبه', 3), ('سه شنبه', 6), (' چهارشنبه', 5), ('پنجشنبه', 6), ('جمعه', 7)])),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
            ],
        ),
    ]
