# Generated by Django 3.2 on 2023-02-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20230208_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendoraddress',
            old_name='address_line1',
            new_name='address',
        ),
    ]
