# Generated by Django 3.2 on 2023-04-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_auto_20230416_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='delivery',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
