# Generated by Django 3.2 on 2023-04-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_vendor_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.CharField(max_length=2)),
                ('image', models.ImageField(upload_to='test')),
            ],
        ),
    ]
