# Generated by Django 3.2 on 2023-04-20 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_vendor_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestUpload',
        ),
        migrations.AddField(
            model_name='vendor',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
