# Generated by Django 3.2 on 2023-02-10 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_rename_address_vendoraddress_address_line1'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_type', to='vendors.vendor'),
        ),
    ]
