# Generated by Django 3.2 on 2023-04-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_auto_20230415_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='english_name',
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
