# Generated by Django 3.2 on 2023-02-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
